server.port: 7001
server.error.include-message: always

logging:
  level:
    root: INFO
    se.magnus: DEBUG

spring:
  data:
    mongodb:
      auto-index-creation: true

---
spring.config.activate.on-profile: docker

server.port: 8080